alter session set "_ORACLE_SCRIPT"=true;
CREATE USER TEST IDENTIFIED BY TEST; -- (User_Name = SGRS and  Selected_Password = SGRS)
GRANT CONNECT, RESOURCE TO TEST;

alter user TEST quota 100M on USERS;

  ------------ Drop All Tables -----------
SELECT 'DROP TABLE "' || table_name || '" CASCADE CONSTRAINTS;' FROM user_tables;

DROP TABLE "SUBSCRIPTION_CONTACT_PIVOT" CASCADE CONSTRAINTS;                    
DROP TABLE "SUBSCRIPTION" CASCADE CONSTRAINTS;                                  
DROP TABLE "WHO_ARE_THEY" CASCADE CONSTRAINTS;                                  
DROP TABLE "TOWNS" CASCADE CONSTRAINTS;                                         
DROP TABLE "TOS" CASCADE CONSTRAINTS;                                           
DROP TABLE "TABLE_ROTATOR" CASCADE CONSTRAINTS;                                 
DROP TABLE "MEMBERSHIP_PRICING" CASCADE CONSTRAINTS;                            
DROP TABLE "MARKETING" CASCADE CONSTRAINTS;                                     
DROP TABLE "GIFT_CERTS" CASCADE CONSTRAINTS;                                    
DROP TABLE "EVENT_CONTACT" CASCADE CONSTRAINTS;                                 
DROP TABLE "EVENTS" CASCADE CONSTRAINTS; 
DROP TABLE "CONTACT_COMITTEE_PIVOT" CASCADE CONSTRAINTS;                        
DROP TABLE "COMMITTEE" CASCADE CONSTRAINTS;                                     
DROP TABLE "CHAMBER_STAFF" CASCADE CONSTRAINTS;
DROP TABLE "BUSINESS" CASCADE CONSTRAINTS;                                      
DROP TABLE "BUSINESS_CONTACT_PIVOT" CASCADE CONSTRAINTS;                        
DROP TABLE "CHAMBER_INFO" CASCADE CONSTRAINTS;                                  
DROP TABLE "CONTACT" CASCADE CONSTRAINTS;                                       
DROP TABLE "ROLES" CASCADE CONSTRAINTS;                                         
DROP TABLE "ADDRESSES" CASCADE CONSTRAINTS;                                     
DROP TABLE "ADVERTISEMENT" CASCADE CONSTRAINTS;                                 
DROP TABLE "BUSINESS_CATEGORIES" CASCADE CONSTRAINTS;                           
DROP TABLE "HOT_DEALS" CASCADE CONSTRAINTS;                                     
DROP TABLE "JOB_POSTINGS" CASCADE CONSTRAINTS;                                  
DROP TABLE "MEMBER_NEWS" CASCADE CONSTRAINTS;  
DROP TABLE "CONTACT_COMMITTEE_PIVOT" CASCADE CONSTRAINTS;  
DROP TABLE "HOME_PAGE" CASCADE CONSTRAINTS; 

Insert into CONTACT (CONTACT_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,SUFFIX,WORK_EMAIL,PERSONAL_EMAIL,WORK_PHONE,CELL_PHONE,VOLUNTEER,LAST_VOLUNTEER_DATE,PRIMARY_CONTACT,RSVP,WHO_ARE_THEY,DISTRICT,PARTY,WHO_ARE_THEY_DATE_FROM,WHO_ARE_THEY_DATE_TO,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE,USERNAME,PASSWORD) values (1,Meeli,Yogesh,Vyas,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'admin','admin');
Insert into "CHAMBER"."ROLES" (ROLE_ID, CONTACT_ID, BUSINESS_ADMIN, BUSINESS_USER_EVENT_POSTING, BUSINESS_USER_JOB_POSTING, BUSINESS_USER_UPDATE_WEBSITE, BUSINESS_USER_MEMBER_NEWS, CHAMBER_STAFF, CONTACT) VALUES ('1', '1', '0', '0', '0', '0', '0', '1', '0');
Insert into CHAMBER_INFO (CHAMBER_INFO_ID,NAME,ADDRESS,CITY,STATE,FACEBOOK_URL,TWITTER_URL,LINKEDIN_URL) values (1,'Mid Maine Chamber of Commerce','chamber address','chamber city','chamber state ','https://www.facebook.com/MidMaineChamber','https://twitter.com/midmainechamber','https://www.linkedin.com/groups/1829258/profile');
Insert into "CHAMBER"."HOME_PAGE" (HOME_PAGE_ID, CHAMBER_INFO_ID) VALUES ('1', '1');


INSERT INTO "CHAMBER"."BUSINESS" (BUSINESS_ID, COMPANY_NAME) VALUES ('1', 'CGI');
INSERT INTO "CHAMBER"."BUSINESS" (BUSINESS_ID, COMPANY_NAME) VALUES ('2', 'AAA');
INSERT INTO "CHAMBER"."BUSINESS" (BUSINESS_ID, COMPANY_NAME) VALUES ('3', 'Collaborative');
INSERT INTO "CHAMBER"."BUSINESS" (BUSINESS_ID, COMPANY_NAME) VALUES ('4', 'AAB');
INSERT INTO "CHAMBER"."BUSINESS" (BUSINESS_ID, COMPANY_NAME) VALUES ('5', 'AAC');
INSERT INTO "CHAMBER"."BUSINESS" (BUSINESS_ID, COMPANY_NAME) VALUES ('6', 'CGA');
commit;

CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;
SELECT 'CREATE SEQUENCE ' || table_name || '_SEQ START WITH 1 INCREMENT BY 1;' FROM user_tables;

